# -*- coding: utf-8 -*-
"""
Catálogo de indicadores do Banco Mundial (WDI) usados para gerar as cartas.

Cada entrada:
  cod        código do indicador na API do Banco Mundial
  curto      rótulo curto (usado no revisao.csv)
  max        pergunta do ranking decrescente (os 10 maiores). None = não gerar.
  min        pergunta do ranking crescente (os 10 menores). None = não gerar.
  unidade    texto mostrado ao juiz
  fmt        como formatar o valor: usd | num | pct | dec | anos | km2
  min_pop    população mínima para o país entrar no ranking (mata microestado)
  regioes    gerar também recortes regionais do ranking decrescente
"""

INDICADORES = [
    # ---------------- economia e comércio ----------------
    dict(cod="NE.EXP.GNFS.CD", curto="exportações",
         max="Quais os países que mais exportam?",
         min=None, unidade="US$", fmt="usd", min_pop=0, regioes=True),
    dict(cod="NE.IMP.GNFS.CD", curto="importações",
         max="Quais os países que mais importam?",
         min=None, unidade="US$", fmt="usd", min_pop=0, regioes=True),
    dict(cod="NY.GDP.MKTP.CD", curto="PIB",
         max="Quais os países com o maior PIB?",
         min=None, unidade="US$", fmt="usd", min_pop=0, regioes=True),
    dict(cod="NY.GDP.PCAP.CD", curto="PIB per capita",
         max="Quais os países com o maior PIB por habitante?",
         min="Quais os países com o menor PIB por habitante?",
         unidade="US$ por habitante", fmt="usd", min_pop=1_000_000, regioes=True),
    dict(cod="NY.GDP.PCAP.PP.CD", curto="PIB per capita PPC",
         max="Quais os países mais ricos por habitante (ajustado por poder de compra)?",
         min=None, unidade="US$ PPC por habitante", fmt="usd", min_pop=1_000_000, regioes=True),
    dict(cod="NY.GDP.MKTP.KD.ZG", curto="crescimento do PIB",
         max="Quais as economias que mais cresceram no ano?",
         min="Quais as economias que mais encolheram no ano?",
         unidade="% ao ano", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="FP.CPI.TOTL.ZG", curto="inflação",
         max="Quais os países com a maior inflação?",
         min=None, unidade="% ao ano", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="FI.RES.TOTL.CD", curto="reservas internacionais",
         max="Quais os países com as maiores reservas internacionais?",
         min=None, unidade="US$", fmt="usd", min_pop=0, regioes=True),
    dict(cod="BX.KLT.DINV.CD.WD", curto="investimento estrangeiro",
         max="Quais os países que mais recebem investimento estrangeiro direto?",
         min=None, unidade="US$", fmt="usd", min_pop=0, regioes=True),
    dict(cod="BX.TRF.PWKR.CD.DT", curto="remessas recebidas",
         max="Quais os países que mais recebem dinheiro enviado por emigrantes?",
         min=None, unidade="US$", fmt="usd", min_pop=0, regioes=True),
    dict(cod="NE.TRD.GNFS.ZS", curto="abertura comercial",
         max="Em quais países o comércio exterior pesa mais na economia?",
         min="Em quais países o comércio exterior pesa menos na economia?",
         unidade="% do PIB", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="TX.VAL.MRCH.CD.WT", curto="exportação de mercadorias",
         max="Quais os países que mais exportam mercadorias (sem contar serviços)?",
         min=None, unidade="US$", fmt="usd", min_pop=0, regioes=True),
    dict(cod="TX.VAL.TECH.CD", curto="exportação alta tecnologia",
         max="Quais os países que mais exportam produtos de alta tecnologia?",
         min=None, unidade="US$", fmt="usd", min_pop=0, regioes=True),
    dict(cod="GC.TAX.TOTL.GD.ZS", curto="carga tributária",
         max="Quais os países que mais arrecadam imposto em relação ao tamanho da economia?",
         min="Quais os países que menos arrecadam imposto em relação à economia?",
         unidade="% do PIB", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="DT.DOD.DECT.CD", curto="dívida externa",
         max="Quais os países em desenvolvimento com a maior dívida externa?",
         min=None, unidade="US$", fmt="usd", min_pop=0, regioes=True),
    dict(cod="SI.POV.GINI", curto="desigualdade (Gini)",
         max="Quais os países mais desiguais do mundo?",
         min="Quais os países menos desiguais do mundo?",
         unidade="índice de Gini", fmt="dec", min_pop=1_000_000, regioes=False),
    dict(cod="SL.UEM.TOTL.ZS", curto="desemprego",
         max="Quais os países com o maior desemprego?",
         min="Quais os países com o menor desemprego?",
         unidade="% da força de trabalho", fmt="pct", min_pop=1_000_000, regioes=True),
    dict(cod="SL.TLF.CACT.FE.ZS", curto="mulheres no trabalho",
         max="Em quais países mais mulheres participam da força de trabalho?",
         min="Em quais países menos mulheres participam da força de trabalho?",
         unidade="% das mulheres 15+", fmt="pct", min_pop=1_000_000, regioes=False),

    # ---------------- população e território ----------------
    dict(cod="SP.POP.TOTL", curto="população",
         max="Quais os países mais populosos?",
         min=None, unidade="habitantes", fmt="num", min_pop=0, regioes=True),
    dict(cod="AG.SRF.TOTL.K2", curto="área",
         max="Quais os maiores países em território?",
         min=None, unidade="km²", fmt="km2", min_pop=0, regioes=True),
    dict(cod="EN.POP.DNST", curto="densidade",
         max="Quais os países mais densamente povoados?",
         min="Quais os países mais vazios (menos gente por km²)?",
         unidade="hab/km²", fmt="dec", min_pop=1_000_000, regioes=False),
    dict(cod="SP.URB.TOTL.IN.ZS", curto="urbanização",
         max="Quais os países mais urbanizados?",
         min="Quais os países onde mais gente vive no campo?",
         unidade="% urbana", fmt="pct", min_pop=1_000_000, regioes=True),
    dict(cod="SP.RUR.TOTL", curto="população rural",
         max="Quais os países com mais gente vivendo na zona rural?",
         min=None, unidade="habitantes", fmt="num", min_pop=0, regioes=True),
    dict(cod="SP.POP.GROW", curto="crescimento populacional",
         max="Quais os países cuja população mais cresce?",
         min="Quais os países cuja população mais encolhe?",
         unidade="% ao ano", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="SP.DYN.TFRT.IN", curto="fecundidade",
         max="Quais os países onde as mulheres têm mais filhos?",
         min="Quais os países onde as mulheres têm menos filhos?",
         unidade="filhos por mulher", fmt="dec", min_pop=1_000_000, regioes=True),
    dict(cod="SP.POP.65UP.TO.ZS", curto="população idosa",
         max="Quais os países mais envelhecidos?",
         min="Quais os países mais jovens?",
         unidade="% com 65 anos ou mais", fmt="pct", min_pop=1_000_000, regioes=True),
    dict(cod="SM.POP.TOTL", curto="imigrantes",
         max="Quais os países que mais abrigam imigrantes?",
         min=None, unidade="pessoas nascidas fora", fmt="num", min_pop=0, regioes=True),
    dict(cod="SM.POP.REFG", curto="refugiados acolhidos", _quebrado=True,
         max="Quais os países que mais acolhem refugiados?",
         min=None, unidade="refugiados", fmt="num", min_pop=0, regioes=True),
    dict(cod="SM.POP.REFG.OR", curto="refugiados de origem", _quebrado=True,
         max="De quais países vêm os refugiados do mundo?",
         min=None, unidade="refugiados originários", fmt="num", min_pop=0, regioes=False),

    # ---------------- saúde ----------------
    dict(cod="SP.DYN.LE00.IN", curto="expectativa de vida",
         max="Quais os países onde as pessoas vivem mais?",
         min="Quais os países onde as pessoas vivem menos?",
         unidade="anos", fmt="anos", min_pop=1_000_000, regioes=True),
    dict(cod="SP.DYN.IMRT.IN", curto="mortalidade infantil",
         max="Quais os países com a maior mortalidade infantil?",
         min="Quais os países com a menor mortalidade infantil?",
         unidade="mortes por mil nascidos", fmt="dec", min_pop=1_000_000, regioes=True),
    dict(cod="SH.XPD.CHEX.PC.CD", curto="gasto com saúde",
         max="Quais os países que mais gastam com saúde por habitante?",
         min=None, unidade="US$ por habitante", fmt="usd", min_pop=1_000_000, regioes=True),
    dict(cod="SH.XPD.CHEX.GD.ZS", curto="saúde % PIB",
         max="Quais os países que mais gastam com saúde em relação à economia?",
         min=None, unidade="% do PIB", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="SH.MED.PHYS.ZS", curto="médicos",
         max="Quais os países com mais médicos por habitante?",
         min="Quais os países com menos médicos por habitante?",
         unidade="médicos por mil hab", fmt="dec", min_pop=1_000_000, regioes=True),
    dict(cod="SH.MED.BEDS.ZS", curto="leitos",
         max="Quais os países com mais leitos de hospital por habitante?",
         min=None, unidade="leitos por mil hab", fmt="dec", min_pop=1_000_000, regioes=False),
    dict(cod="SH.ALC.PCAP.LI", curto="álcool",
         max="Quais os países que mais bebem?",
         min="Quais os países que menos bebem?",
         unidade="litros de álcool puro por adulto/ano", fmt="dec", min_pop=1_000_000, regioes=True),
    dict(cod="SH.PRV.SMOK", curto="fumantes",
         max="Quais os países com mais fumantes?",
         min="Quais os países com menos fumantes?",
         unidade="% dos adultos", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="SH.STA.OWGH.ME.ZS", curto="sobrepeso infantil",
         max="Quais os países com mais crianças acima do peso?",
         min=None, unidade="% das crianças <5", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="SH.STA.SUIC.P5", curto="suicídio",
         max="Quais os países com a maior taxa de suicídio?",
         min="Quais os países com a menor taxa de suicídio?",
         unidade="por 100 mil hab", fmt="dec", min_pop=1_000_000, regioes=True),
    dict(cod="SH.DYN.NCOM.ZS", curto="doenças crônicas",
         max="Em quais países é maior o risco de morrer de doença crônica?",
         min="Em quais países é menor o risco de morrer de doença crônica?",
         unidade="% de risco entre 30 e 70 anos", fmt="pct", min_pop=1_000_000, regioes=False),

    # ---------------- educação, ciência, tecnologia ----------------
    dict(cod="SE.XPD.TOTL.GD.ZS", curto="gasto com educação",
         max="Quais os países que mais gastam com educação em relação à economia?",
         min=None, unidade="% do PIB", fmt="pct", min_pop=1_000_000, regioes=True),
    dict(cod="SE.TER.ENRR", curto="ensino superior",
         max="Quais os países com a maior taxa de matrícula no ensino superior?",
         min="Quais os países com a menor taxa de matrícula no ensino superior?",
         unidade="matrícula bruta, % da faixa etária", fmt="pct", min_pop=1_000_000, regioes=True),
    dict(cod="SE.ADT.LITR.ZS", curto="alfabetização",
         max=None,
         min="Quais os países com a menor taxa de alfabetização?",
         unidade="% de adultos alfabetizados", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="GB.XPD.RSDV.GD.ZS", curto="P&D",
         max="Quais os países que mais investem em pesquisa e desenvolvimento?",
         min=None, unidade="% do PIB", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="SP.POP.SCIE.RD.P6", curto="pesquisadores",
         max="Quais os países com mais pesquisadores por habitante?",
         min=None, unidade="por milhão de hab", fmt="num", min_pop=1_000_000, regioes=False),
    dict(cod="IP.PAT.RESD", curto="patentes",
         max="Quais os países que mais registram patentes?",
         min=None, unidade="pedidos de residentes", fmt="num", min_pop=0, regioes=True),
    dict(cod="IT.NET.USER.ZS", curto="internet",
         max="Quais os países mais conectados à internet?",
         min="Quais os países menos conectados à internet?",
         unidade="% da população", fmt="pct", min_pop=1_000_000, regioes=True),
    dict(cod="IT.CEL.SETS.P2", curto="celulares",
         max="Quais os países com mais linhas de celular por habitante?",
         min=None, unidade="por 100 hab", fmt="dec", min_pop=1_000_000, regioes=True),
    dict(cod="IT.NET.BBND.P2", curto="banda larga",
         max="Quais os países com mais assinaturas de banda larga fixa por habitante?",
         min=None, unidade="por 100 hab", fmt="dec", min_pop=1_000_000, regioes=False),

    # ---------------- energia, meio ambiente, agricultura ----------------
    dict(cod="EG.ELC.ACCS.ZS", curto="acesso à eletricidade",
         max=None,
         min="Quais os países onde menos gente tem energia elétrica em casa?",
         unidade="% da população", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="EG.ELC.RNEW.ZS", curto="energia renovável",
         max="Quais os países com a matriz elétrica mais renovável?",
         min="Quais os países com a matriz elétrica menos renovável?",
         unidade="% da eletricidade", fmt="pct", min_pop=1_000_000, regioes=True),
    dict(cod="EG.USE.PCAP.KG.OE", curto="consumo de energia",
         max="Quais os países que mais consomem energia por habitante?",
         min=None, unidade="kg equiv. de petróleo por hab", fmt="num", min_pop=1_000_000, regioes=False),
    dict(cod="EN.GHG.CO2.PC.CE.AR5", curto="CO2 per capita",
         max="Quais os países que mais emitem CO₂ por habitante?",
         min=None, unidade="toneladas por hab", fmt="dec", min_pop=1_000_000, regioes=True),
    dict(cod="EN.GHG.CO2.MT.CE.AR5", curto="CO2 total",
         max="Quais os países que mais emitem CO₂?",
         min=None, unidade="megatoneladas", fmt="num", min_pop=0, regioes=True),
    dict(cod="AG.LND.FRST.ZS", curto="florestas",
         max="Quais os países mais cobertos por floresta?",
         min="Quais os países com menos floresta?",
         unidade="% do território", fmt="pct", min_pop=1_000_000, regioes=True),
    dict(cod="AG.LND.ARBL.ZS", curto="terra arável",
         max="Quais os países com a maior proporção de terra agricultável?",
         min=None, unidade="% do território", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="ER.PTD.TOTL.ZS", curto="áreas protegidas",
         max="Quais os países que mais protegem seu território e mar?",
         min="Quais os países que menos protegem seu território e mar?",
         unidade="% da área", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="AG.PRD.CREL.MT", curto="produção de cereais",
         max="Quais os países que mais produzem cereais?",
         min=None, unidade="toneladas", fmt="num", min_pop=0, regioes=True),
    dict(cod="ER.H2O.FWTL.K3", curto="uso de água",
         max="Quais os países que mais consomem água doce?",
         min=None, unidade="bilhões de m³/ano", fmt="dec", min_pop=0, regioes=False),
    dict(cod="SL.AGR.EMPL.ZS", curto="emprego na agricultura",
         max="Quais os países onde mais gente trabalha na agricultura?",
         min="Quais os países onde menos gente trabalha na agricultura?",
         unidade="% dos empregados", fmt="pct", min_pop=1_000_000, regioes=True),
    dict(cod="NV.IND.MANF.ZS", curto="indústria",
         max="Quais os países mais industrializados (indústria no PIB)?",
         min=None, unidade="% do PIB", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="NY.GDP.PETR.RT.ZS", curto="renda do petróleo",
         max="Quais os países mais dependentes do petróleo?",
         min=None, unidade="% do PIB", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="NY.GDP.MINR.RT.ZS", curto="renda mineral",
         max="Quais os países mais dependentes da mineração?",
         min=None, unidade="% do PIB", fmt="pct", min_pop=1_000_000, regioes=False),

    # ---------------- transporte, turismo, segurança, política ----------------
    dict(cod="ST.INT.ARVL", curto="turistas recebidos",
         max="Quais os países que mais recebem turistas?",
         min=None, unidade="chegadas por ano", fmt="num", min_pop=0, regioes=True),
    dict(cod="ST.INT.RCPT.CD", curto="receita de turismo",
         max="Quais os países que mais faturam com turismo?",
         min=None, unidade="US$", fmt="usd", min_pop=0, regioes=True),
    dict(cod="ST.INT.XPND.CD", curto="gasto de turismo",
         max="Quais os países cujos cidadãos mais gastam viajando para fora?",
         min=None, unidade="US$", fmt="usd", min_pop=0, regioes=False),
    dict(cod="IS.AIR.PSGR", curto="passageiros aéreos",
         max="Quais os países que mais transportam passageiros de avião?",
         min=None, unidade="passageiros por ano", fmt="num", min_pop=0, regioes=True),
    dict(cod="IS.SHP.GOOD.TU", curto="contêineres",
         max="Quais os países com o maior movimento de contêineres nos portos?",
         min=None, unidade="TEU por ano", fmt="num", min_pop=0, regioes=False),
    dict(cod="VC.IHR.PSRC.P5", curto="homicídios",
         max="Quais os países com a maior taxa de homicídio?",
         min="Quais os países com a menor taxa de homicídio?",
         unidade="por 100 mil hab", fmt="dec", min_pop=1_000_000, regioes=True),
    dict(cod="MS.MIL.XPND.CD", curto="gasto militar",
         max="Quais os países que mais gastam com as forças armadas?",
         min=None, unidade="US$", fmt="usd", min_pop=0, regioes=True),
    dict(cod="MS.MIL.XPND.GD.ZS", curto="militar % PIB",
         max="Quais os países mais militarizados em relação ao tamanho da economia?",
         min=None, unidade="% do PIB", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="MS.MIL.TOTL.P1", curto="militares",
         max="Quais os países com as maiores forças armadas?",
         min=None, unidade="militares na ativa", fmt="num", min_pop=0, regioes=True),
    dict(cod="SG.GEN.PARL.ZS", curto="mulheres no parlamento",
         max="Quais os países com mais mulheres no parlamento?",
         min="Quais os países com menos mulheres no parlamento?",
         unidade="% das cadeiras", fmt="pct", min_pop=1_000_000, regioes=True),
    # ---------------- lote 2: mais variedade ----------------
    dict(cod="BM.TRF.PWKR.CD.DT", curto="remessas enviadas",
         max="De quais países mais sai dinheiro enviado por imigrantes?",
         min=None, unidade="US$", fmt="usd", min_pop=0, regioes=True),
    dict(cod="GC.DOD.TOTL.GD.ZS", curto="dívida pública",
         max="Quais os países mais endividados em relação à economia?",
         min=None, unidade="% do PIB", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="FR.INR.LEND", curto="juros",
         max="Quais os países com os juros mais altos?",
         min="Quais os países com os juros mais baixos?",
         unidade="% ao ano", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="CM.MKT.LCAP.GD.ZS", curto="bolsa de valores",
         max="Em quais países a bolsa vale mais em relação à economia?",
         min=None, unidade="% do PIB", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="GC.XPN.TOTL.GD.ZS", curto="gasto público",
         max="Quais os países onde o governo mais gasta em relação à economia?",
         min=None, unidade="% do PIB", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="SI.DST.10TH.10", curto="fatia dos 10% mais ricos",
         max="Em quais países os 10% mais ricos ficam com a maior fatia da renda?",
         min=None, unidade="% da renda", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="SH.STA.TRAF.P5", curto="mortes no trânsito",
         max="Quais os países com mais mortes no trânsito?",
         min="Quais os países com menos mortes no trânsito?",
         unidade="por 100 mil hab", fmt="dec", min_pop=1_000_000, regioes=True),
    dict(cod="SN.ITK.DEFC.ZS", curto="subnutrição",
         max="Em quais países a maior fatia da população passa fome?",
         min=None, unidade="% da população", fmt="pct", min_pop=1_000_000, regioes=True),
    dict(cod="SH.STA.STNT.ZS", curto="nanismo infantil",
         max="Em quais países mais crianças têm o crescimento comprometido?",
         min=None, unidade="% das crianças <5", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="SH.H2O.BASW.ZS", curto="água potável",
         max=None,
         min="Quais os países onde menos gente tem acesso a água potável?",
         unidade="% da população", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="SH.STA.BASS.ZS", curto="saneamento",
         max=None,
         min="Quais os países onde menos gente tem saneamento básico?",
         unidade="% da população", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="SP.ADO.TFRT", curto="gravidez na adolescência",
         max="Quais os países com mais gravidez na adolescência?",
         min="Quais os países com menos gravidez na adolescência?",
         unidade="nascimentos por mil meninas de 15 a 19", fmt="dec",
         min_pop=1_000_000, regioes=True),
    dict(cod="SH.DYN.AIDS.ZS", curto="HIV",
         max="Quais os países com a maior prevalência de HIV?",
         min=None, unidade="% dos adultos", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="SH.TBS.INCD", curto="tuberculose",
         max="Quais os países com mais casos de tuberculose por habitante?",
         min=None, unidade="por 100 mil hab", fmt="num", min_pop=1_000_000, regioes=True),
    dict(cod="SH.IMM.MEAS", curto="vacina de sarampo",
         max=None,
         min="Quais os países que menos vacinam contra sarampo?",
         unidade="% das crianças", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="SL.TLF.0714.ZS", curto="trabalho infantil",
         max="Quais os países com mais trabalho infantil?",
         min=None, unidade="% das crianças de 7 a 14", fmt="pct",
         min_pop=1_000_000, regioes=False),
    dict(cod="EN.ATM.PM25.MC.M3", curto="poluição do ar",
         max="Quais os países com o ar mais poluído?",
         min="Quais os países com o ar mais limpo?",
         unidade="µg/m³ de material particulado", fmt="dec",
         min_pop=1_000_000, regioes=True),
    dict(cod="EG.FEC.RNEW.ZS", curto="renováveis no consumo",
         max="Quais os países que mais usam energia renovável no consumo total?",
         min="Quais os países que menos usam energia renovável?",
         unidade="% do consumo final", fmt="pct", min_pop=1_000_000, regioes=True),
    dict(cod="EG.IMP.CONS.ZS", curto="dependência energética",
         max="Quais os países mais dependentes de energia importada?",
         min=None, unidade="% da energia usada", fmt="pct", min_pop=1_000_000, regioes=False),
    dict(cod="TX.VAL.FUEL.ZS.UN", curto="exportação de combustível",
         max="Em quais países combustível é a maior parte do que se exporta?",
         min=None, unidade="% das exportações", fmt="pct", min_pop=1_000_000, regioes=True),
    dict(cod="TX.VAL.AGRI.ZS.UN", curto="exportação agrícola",
         max="Em quais países produto agrícola é a maior parte do que se exporta?",
         min=None, unidade="% das exportações", fmt="pct", min_pop=1_000_000, regioes=True),
    dict(cod="ER.H2O.INTR.PC", curto="água doce por habitante",
         max="Quais os países com mais água doce por habitante?",
         min="Quais os países com menos água doce por habitante?",
         unidade="m³ por hab/ano", fmt="num", min_pop=1_000_000, regioes=False),
    dict(cod="AG.LND.PRCP.MM", curto="chuva",
         max="Quais os países onde mais chove?",
         min="Quais os países onde menos chove?",
         unidade="mm por ano", fmt="num", min_pop=1_000_000, regioes=True),
    dict(cod="SE.COM.DURS", curto="escola obrigatória",
         max="Quais os países com mais anos de escola obrigatória?",
         min="Quais os países com menos anos de escola obrigatória?",
         unidade="anos", fmt="dec", min_pop=1_000_000, regioes=False),
    dict(cod="IC.REG.DURS", curto="abrir empresa", _quebrado=True,
         max="Em quais países demora mais pra abrir uma empresa?",
         min=None, unidade="dias", fmt="dec", min_pop=1_000_000, regioes=False),
    dict(cod="SP.DYN.CDRT.IN", curto="taxa de mortalidade",
         max="Quais os países onde mais gente morre por habitante?",
         min="Quais os países onde menos gente morre por habitante?",
         unidade="mortes por mil hab", fmt="dec", min_pop=1_000_000, regioes=True),
    dict(cod="SE.SEC.ENRR", curto="ensino médio",
         max=None,
         min="Quais os países com a menor matrícula no ensino médio?",
         unidade="matrícula bruta, % da faixa etária", fmt="pct",
         min_pop=1_000_000, regioes=False),
    dict(cod="NV.AGR.TOTL.ZS", curto="agricultura no PIB",
         max="Em quais países a agricultura mais pesa na economia?",
         min=None, unidade="% do PIB", fmt="pct", min_pop=1_000_000, regioes=True),
    dict(cod="IS.RRS.TOTL.KM", curto="ferrovias",
         max="Quais os países com a maior malha ferroviária?",
         min=None, unidade="km de linha", fmt="num", min_pop=0, regioes=False),
    dict(cod="AG.PRD.LVSK.XD", curto="pecuária",
         max="Quais os países que mais aumentaram a produção pecuária?",
         min=None, unidade="índice (2014-16 = 100)", fmt="dec",
         min_pop=1_000_000, regioes=False),
]

# --------------------------------------------------------------------------
# Regiões. As do Banco Mundial não servem pra jogo: ele junta "Europa e Ásia
# Central" e renomeou o Oriente Médio pra "Middle East, North Africa,
# Afghanistan & Pakistan". Aqui a região é montada a partir da região do WB
# com as correções abaixo, e o nome é o que a pessoa fala na mesa.
# --------------------------------------------------------------------------

# Ficam DENTRO de "Europe & Central Asia" no WB, mas são Ásia pro jogo.
ASIA_CENTRAL = {"KAZ", "KGZ", "TJK", "TKM", "UZB", "ARM", "AZE", "GEO"}
# Ficam em "East Asia & Pacific" no WB, mas são Oceania.
OCEANIA = {"AUS", "NZL", "FJI", "FSM", "KIR", "MHL", "NRU", "PLW", "PNG",
           "SLB", "TON", "TUV", "VUT", "WSM"}
# Ficam no bucket do Oriente Médio no WB, mas são África.
AFRICA_NORTE = {"DZA", "EGY", "LBY", "MAR", "TUN", "DJI"}
# Ficam no bucket do Oriente Médio no WB, mas são Ásia.
ORIENTE_MEDIO = {"ARE", "BHR", "IRN", "IRQ", "ISR", "JOR", "KWT", "LBN", "OMN",
                 "PSE", "QAT", "SAU", "SYR", "YEM", "AFG", "PAK"}
# Malta está no bucket do Oriente Médio no WB. É Europa.
EUROPA_EXTRA = {"MLT"}

UE27 = {"AUT", "BEL", "BGR", "CYP", "CZE", "DEU", "DNK", "ESP", "EST", "FIN",
        "FRA", "GRC", "HRV", "HUN", "IRL", "ITA", "LTU", "LUX", "LVA", "MLT",
        "NLD", "POL", "PRT", "ROU", "SVK", "SVN", "SWE"}


def regiao_de(iso3, regiao_wb):
    """Região do país pro jogo. None = não entra em recorte regional."""
    if iso3 in OCEANIA:
        return None                       # 14 países: não dá top 10 honesto
    if iso3 in ASIA_CENTRAL or iso3 in ORIENTE_MEDIO:
        return "Ásia"
    if iso3 in AFRICA_NORTE:
        return "África"
    if iso3 in EUROPA_EXTRA:
        return "Europa"
    return {
        "Europe & Central Asia": "Europa",
        "Sub-Saharan Africa": "África",
        "East Asia & Pacific": "Ásia",
        "South Asia": "Ásia",
        "Latin America & Caribbean": "Américas",
        "North America": "Américas",
    }.get(regiao_wb)


# nome da região -> como ela entra no fim da pergunta
REGIOES = {
    "Europa": "na Europa",
    "África": "na África",
    "Ásia": "na Ásia",
    "Américas": "nas Américas",
    "União Europeia": "na União Europeia",
}

# Cartas que o gerador monta certo mas que são ruins de jogar. Cortadas pelo
# texto exato da pergunta. "Mais populosos" é o caso clássico: todo mundo
# acerta seis de cara e a rodada acaba sem graça.
VETADAS = {
    "Quais os países mais populosos?",
}

# Entidades do Banco Mundial que não são países soberanos. Removidas por padrão.
NAO_SOBERANOS = {
    "ABW", "ASM", "BMU", "CHI", "CUW", "CYM", "FRO", "GIB", "GRL", "GUM",
    "HKG", "IMN", "MAC", "MAF", "MNP", "NCL", "PRI", "PYF", "SXM", "TCA",
    "VGB", "VIR",
}

# Nomes que o Wikidata dá errado ou não dá pro nosso gosto.
NOMES_EXTRA = {
    "NLD": "Países Baixos",
    "CHN": "China",
    "IRL": "Irlanda",
    "BFA": "Burkina Faso",
    "BHR": "Bahrein",
    "BEN": "Benin",
    "KIR": "Kiribati",
    "BWA": "Botsuana",
    "XKX": "Kosovo",
    "MMR": "Mianmar",
    "MUS": "Maurício",
    "CIV": "Costa do Marfim",
    "COD": "República Democrática do Congo",
    "COG": "República do Congo",
    "SWZ": "Essuatíni",
    "TLS": "Timor-Leste",
    "PSE": "Palestina",
    "CPV": "Cabo Verde",
}

# Apelidos que brasileiro fala na mesa e que o Wikidata pode não ter.
# Cresce jogando: nome que o juiz não reconhecer, anota aqui.
APELIDOS_EXTRA = {
    "USA": ["eua", "estados unidos", "america", "estados unidos da america", "us"],
    "GBR": ["inglaterra", "reino unido", "gra bretanha", "uk", "britanica", "escocia"],
    "NLD": ["holanda", "paises baixos"],
    "KOR": ["coreia do sul", "coreia", "sul coreia"],
    "PRK": ["coreia do norte", "norte coreia"],
    "ARE": ["emirados", "emirados arabes", "dubai", "abu dhabi"],
    "SAU": ["arabia saudita", "arabia"],
    "RUS": ["russia", "uniao sovietica"],
    "CZE": ["republica tcheca", "tchequia", "chequia"],
    "CIV": ["costa do marfim"],
    "MMR": ["mianmar", "birmania", "myanmar"],
    "COD": ["republica democratica do congo", "rd congo", "rdc", "congo kinshasa", "zaire"],
    "COG": ["republica do congo", "congo brazzaville"],
    "CHE": ["suica"],
    "SWE": ["suecia"],
    "CHN": ["china", "republica popular da china"],
    "TUR": ["turquia", "turquiye"],
    "EGY": ["egito"],
    "ZAF": ["africa do sul"],
    "IRN": ["ira", "persia"],
    "IRQ": ["iraque"],
    "DEU": ["alemanha"],
    "AUT": ["austria"],
    "AUS": ["australia"],
    "NZL": ["nova zelandia"],
    "IND": ["india"],
    "IDN": ["indonesia"],
    "VNM": ["vietna", "vietnam"],
    "THA": ["tailandia"],
    "PHL": ["filipinas"],
    "MYS": ["malasia"],
    "SGP": ["singapura"],
    "JPN": ["japao"],
    "MEX": ["mexico"],
    "ARG": ["argentina"],
    "CHL": ["chile"],
    "COL": ["colombia"],
    "PER": ["peru"],
    "VEN": ["venezuela"],
    "BOL": ["bolivia"],
    "PRY": ["paraguai"],
    "URY": ["uruguai"],
    "BRA": ["brasil", "br"],
    "PRT": ["portugal"],
    "ESP": ["espanha"],
    "FRA": ["franca"],
    "ITA": ["italia"],
    "GRC": ["grecia"],
    "POL": ["polonia"],
    "NOR": ["noruega"],
    "DNK": ["dinamarca"],
    "FIN": ["finlandia"],
    "ISL": ["islandia"],
    "IRL": ["irlanda"],
    "BEL": ["belgica"],
    "HUN": ["hungria"],
    "ROU": ["romenia"],
    "BGR": ["bulgaria"],
    "HRV": ["croacia"],
    "SRB": ["servia"],
    "UKR": ["ucrania"],
    "BLR": ["bielorrussia", "belarus"],
    "KAZ": ["cazaquistao"],
    "UZB": ["uzbequistao"],
    "PAK": ["paquistao"],
    "BGD": ["bangladesh"],
    "LKA": ["sri lanka", "ceilao"],
    "NPL": ["nepal"],
    "AFG": ["afeganistao"],
    "ISR": ["israel"],
    "PSE": ["palestina", "faixa de gaza", "cisjordania"],
    "SYR": ["siria"],
    "LBN": ["libano"],
    "JOR": ["jordania"],
    "MAR": ["marrocos"],
    "DZA": ["argelia"],
    "TUN": ["tunisia"],
    "LBY": ["libia"],
    "SDN": ["sudao"],
    "SSD": ["sudao do sul"],
    "ETH": ["etiopia", "abissinia"],
    "KEN": ["quenia"],
    "TZA": ["tanzania"],
    "UGA": ["uganda"],
    "NGA": ["nigeria"],
    "GHA": ["gana"],
    "SEN": ["senegal"],
    "CMR": ["camaroes"],
    "AGO": ["angola"],
    "MOZ": ["mocambique"],
    "ZWE": ["zimbabue", "rodesia"],
    "ZMB": ["zambia"],
    "BWA": ["botsuana", "botswana"],
    "NAM": ["namibia"],
    "MDG": ["madagascar"],
    "CUB": ["cuba"],
    "DOM": ["republica dominicana"],
    "HTI": ["haiti"],
    "JAM": ["jamaica"],
    "CRI": ["costa rica"],
    "PAN": ["panama"],
    "GTM": ["guatemala"],
    "HND": ["honduras"],
    "SLV": ["el salvador"],
    "NIC": ["nicaragua"],
    "ECU": ["equador"],
    "CAN": ["canada"],
    "TWN": ["taiwan", "formosa"],
    "QAT": ["catar", "qatar"],
    "KWT": ["kuwait", "kuweit"],
    "OMN": ["oma", "oman"],
    "YEM": ["iemen"],
    "AZE": ["azerbaijao"],
    "GEO": ["georgia"],
    "ARM": ["armenia"],
    "MNG": ["mongolia"],
    "KHM": ["camboja"],
    "LAO": ["laos"],
    "TLS": ["timor leste"],
    "PNG": ["papua nova guine"],
    "FJI": ["fiji"],
    "LUX": ["luxemburgo"],
    "SVK": ["eslovaquia"],
    "SVN": ["eslovenia"],
    "EST": ["estonia"],
    "LVA": ["letonia"],
    "LTU": ["lituania"],
    "ALB": ["albania"],
    "MKD": ["macedonia do norte", "macedonia"],
    "BIH": ["bosnia", "bosnia e herzegovina"],
    "MNE": ["montenegro"],
    "XKX": ["kosovo"],
    "MDA": ["moldavia", "moldova"],
    "CYP": ["chipre"],
    "MLT": ["malta"],
}
